### PR TITLE
Updating ML.NET to the latest version - 0.11.0-preview-27428-4.

### PR DESCRIPTION
**Pull request by eerhardt**
@SteveSandersonMS @rustd

### CODE REVIEW

**Comment by rustd** [comment]
Looks good to me

**Comment by SteveSandersonMS** [comment]
@eerhardt Is the `[ThreadStatic]` just because `PredictionEngine` isn't thread-safe? If so, this is fine as a quick solution, but longer term, would you recommend that:

 1. We have a single `static` instance and control calls to it by wrapping them in a `lock`
 2. Or, we use DI to produce a separate instance per context, so we can avoid locks and threadstatics

Option 2 generally sounds better, but it's only good as long as `PredictionEngine` is really cheap to create and doesn't require disposal. If it's expensive to create, we'd be better having some sort of object pool of them.

**Comment by eerhardt** [comment]
I used the `[ThreadStatic]` as a cheap "pooling" mechanism. `PredictionEngine` instances are not cheap to create, and they are not thread-safe. Using `[ThreadStatic]` piggybacks on the thread pool - if the thread gets reused, the `PredictionEngine` gets reused. When the thread is removed from the pool, the `PredictionEngine` gets GC'd.

I'd be fine with `lock`ing around a single static PredictionEngine, or using https://www.nuget.org/packages/Microsoft.Extensions.ObjectPool/.

Another thing to consider in this realm is that the way things are written now the prediction engine gets called a lot. Potentially adding a 'delay while typing' would decrease the number of calls substantially.

**Comment by SteveSandersonMS** [comment]
OK, makes sense. I'll merge this as-is then, and will consider your advice any time I update this demo further.

**Pull request merged**
